---
# tasks file for homebrew
- name: Install requirements
  apt:
    name:
      - build-essential
      - procps
      - curl
      - file
      - git
    state: present
    update_cache: yes

- name: Install Homebrew
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
