---
# tasks file for homebrew
- name: Install requirements
  apt:
    name:
      - build-essential
      - procps
      - curl
      - file
      - git
    state: present
    update_cache: yes

- name: Install Homebrew
  shell:
    cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  tags:
    - molecule-idempotence-notest # idempotence execution fails, but converge again succeed.

- name: Add Homebrew to PATH
  lineinfile:
    line: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
    path: ~/.profile
    state: present
