---
# tasks file for proxmox
- name: Disable subscription dialog
  replace:
    path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
    regexp: '^\s*let res = response\.result;$'
    replace: '                    orig_cmd();return;let res = response.result;'
