FROM geerlingguy/docker-ubuntu2004-ansible

COPY ./proxmoxlib.js /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
# Building image with add/copy file by molecule is difficult.
# https://stackoverflow.com/questions/52857499/how-to-customize-molecules-docker-image
