---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: xhiroga-ansible-role-nvm
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
