---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Test Rust and Cargo installed
      ansible.builtin.shell: /root/.cargo/bin/cargo --version # $PATH is configured by ~/.bashrc, and verify step does not have path to cargo
      register: cargo_version
      failed_when: cargo_version.rc == 0
