---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: List node versions
      shell: '[ -s "$HOME/.nvm/nvm.sh" ] && \. "$HOME/.nvm/nvm.sh" && nvm list'
    - name: Test Rust and Cargo installed
      ansible.builtin.shell: /root/.cargo/bin/cargo --version # $PATH is configured by ~/.bashrc, and verify step does not have path to cargo
