---
# tasks file for vm_template
# [Proxmox VE Full Course: Class 6 \- Creating Virtual Machine Templates \- YouTube](https://www.youtube.com/watch?v=t3Yv4OOYcLs)
- name: Install cloud-init
  apt:
    autoclean: yes
    autoremove: yes
    name: cloud-init # resetting ssh host keys

- name: Remove ssh_host_files which will be created by cloud-init
  # [But the file module does not provide any support for wildcards\.](https://www.mydailytutorials.com/ansible-delete-multiple-files-directories-ansible/)
  # command does not looks to handle wildcard
  ansible.builtin.shell: rm -f /etc/ssh/ssh_host_*

- name: Truncate machine id
  ansible.builtin.command:
    cmd: truncate -s 0 /etc/machine-id

- name: Symbolic link to machine id
  ansible.builtin.file:
    path: /var/lib/dbus/machine-id
    src: /etc/machine-id
    state: link

- name: Clean database and packages
  ansible.builtin.command:
    cmd: apt clean

- name: Remove all orphan packages
  ansible.builtin.command:
    cmd: apt autoremove

# [Running "sudo cloud\-init clean" as a last step before converting the vm into a template solved the problem for me](https://www.youtube.com/watch?v=t3Yv4OOYcLs)
- name: Clean cloud-init
  ansible.builtin.command:
    cmd: cloud-init clean
