---
# tasks file for windows
- name: Modify Registry
  ansible.windows.win_regedit:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    data: "{{ item.data }}"
    datatype: '{{ item.datatype | default("dword") }}'
  with_items:
    # エクスプローラーの「登録されている拡張子は表示しない」の無効化
    - key: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
      value: HideFileExt
      data: 0

# [Enable WSL and SSH into Windows with Bash \| SimpleBackups Docs](https://simplebackups.com/docs/knowledge-base/tutorials/enable-wsl-and-ssh-into-windows-with-bash.html)
- name: Enable ssh
  ansible.windows.win_shell: Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0

- name: Enable ssh agent
  ansible.windows.win_service:
    name: ssh-agent
    state: started
    start_mode: auto

- name: Enable ssh agent
  ansible.windows.win_service:
    name: sshd
    state: started
    start_mode: auto

- name: Copy ssh key
  ansible.windows.win_get_url:
    url: "{{ administrators_authorized_keys_url }}"
    dest: C:\ProgramData\ssh\administrators_authorized_keys

- name: Disable inheritance
  ansible.windows.win_acl_inheritance:
    path: C:\ProgramData\ssh\administrators_authorized_keys
    state: absent

- name: Appropriately ACL the authorized_keys file on your server for Administrators
  ansible.windows.win_acl:
    user: Administrators
    path: C:\ProgramData\ssh\administrators_authorized_keys
    rights: FullControl
    type: allow
    state: present

- name: Appropriately ACL the authorized_keys file on your server for SYSTEM
  ansible.windows.win_acl:
    user: SYSTEM
    path: C:\ProgramData\ssh\administrators_authorized_keys
    rights: FullControl
    type: allow
    state: present

- name: List winget packages
  ansible.windows.win_shell: winget list
  register: winget_list

# アプリケーション実行時にインストールするとエラーになることが多いので、初回に限る。
- name: Install packages
  # In the first time, manually put [Y] Yes to agreements terms.
  ansible.windows.win_shell: winget install {{ item }}
  loop: "{{ winget_packages }}"
  when: item not in winget_list.stdout
