---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Lint file
    shell: plutil -lint {{ com_apple_dock_plist }}
  - name: Copy expected file
    ansible.builtin.copy:
      src: "{{ com_apple_dock_expected_plist_file }}"
      dest: "$HOME"
      mode: 666
  - name: Diff files
    ansible.builtin.shell: diff {{ com_apple_dock_plist }} "$HOME/{{ com_apple_dock_expected_plist_file }}"
  vars:
    com_apple_dock_plist: '~/Library/Preferences/com.apple.dock.plist'
    com_apple_dock_expected_plist_file: 'com.apple.dock.expected.plist'
