---
- name: Check git-secrets installed
  ansible.builtin.shell: git secrets --list
  changed_when: false
  ignore_errors: true
  register: has_git_secrets_list

- name: Check brew installed
  ansible.builtin.shell: brew --version
  changed_when: false
  ignore_errors: true
  register: has_brew_version

- name: Install git-secrets by brew
  ansible.builtin.shell: brew install git-secrets
  when: has_git_secrets_list.rc == 1 and has_brew_version.rc == 0

- name: Install git-secrets
  ansible.builtin.shell: |
    git clone https://github.com/awslabs/git-secrets.git ~/git-secrets
    make -C ~/git-secrets install
  when: has_git_secrets_list.rc == 1 and has_brew_version.rc != 0

- name: Update git-secrets
  ansible.builtin.shell: |
    git secrets --register-aws --global
    git secrets --install ~/.git-templates/git-secrets
    git config --global init.templateDir ~/.git-templates/git-secrets
  changed_when: false
