## References
# [nvm\-sh/nvm: Node Version Manager \- POSIX\-compliant bash script to manage multiple active node\.js versions](https://github.com/nvm-sh/nvm#ansible)
# [moviedo/ansible\-role\-nvm: Ansible role for using NVM, Node Version Manager, locally\.](https://github.com/moviedo/ansible-role-nvm)
---
- name: Install nvm
  ansible.builtin.shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh | bash
  args:
    creates: "$HOME/.nvm/nvm.sh"

- name: Install node versions
  ansible.builtin.shell: '[ -s "$HOME/.nvm/nvm.sh" ] && \. "$HOME/.nvm/nvm.sh" && nvm install {{ item }}'
  loop: "{{ nvm_node_versions }}"
  tags:
    - molecule-idempotence-notest
