---
# tasks file for ubuntu_rdp
- name: install ubuntu desktop
  apt:
    name:
      - xrdp

# Enabled by default
# - name: Enable xrdp services
#   systemd:
#     name: xrdp.service
#     state: restarted
#     enabled: yes

# - name: Enable xrdp services
#   systemd:
#     name: xrdp-sesman.service
#     state: restarted
#     enabled: yes

- name: Copy xsession file
  copy:
    src: .xsessionrc
    dest: ~/.xsessionrc
  vars:
    ansible_become: false

- name: Copy polkit config file
  copy:
    src: xrdp-color-manager.pkla
    dest: /etc/polkit-1/localauthority/50-local.d/xrdp-color-manager.pkla

- name: Restart polkit
  systemd:
    name: polkit.service
    state: restarted
    enabled: yes

## References
# - [AWS EC2でデスクトップ環境をつくる ～ Ubuntu Server 18\.04 LTS GNOME編～ \- Qiita](https://qiita.com/osugizmo/items/21578272ae2db05ab001)
# - [第621回 Ubuntu 20\.04 LTSでxrdpを使用する：Ubuntu Weekly Recipe｜gihyo\.jp … 技術評論社](https://gihyo.jp/admin/serial/01/ubuntu-recipe/0621)
